# Generated by Django 4.2.1 on 2023-06-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.CharField(max_length=2048, verbose_name='describe'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=128, verbose_name='titre'),
        ),
    ]
