# Generated by Django 4.2.1 on 2023-06-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rthome', '0002_alter_ticket_description_alter_ticket_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.CharField(max_length=2048, verbose_name='description'),
        ),
    ]
