# Generated by Django 4.2.1 on 2023-06-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userfollows_user_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollows',
            name='followed_user_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='userfollows',
            name='user_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
